### ISSUE TITLE
Saying Hello to Thomas

### ISSUE THREAD

**Issue by maltefiala** [borg-backup/borg-backup.github.io#1]
Hej Thomas!

Just yesterday I was looking up attic to encounter many motivated people being let down by the original maintainer. Today, I just wanted to ask how you feel about forking attic and now there is this repository.

Would be great to stay in touch,
Malte

**Comment by maltefiala** [comment]
Hahaha, I just remembered jborg develops attic which makes this repository name even better :D

**Comment by ThomasWaldmann** [comment]
Thanks for heads up, let's see how https://github.com/jborg/attic/issues/217 develops.

**Comment by maltefiala** [comment]
"Being let down" was a bit harsh. I understand there may be reasons for not wanting to collaborate, like fear of messy code or poor programming. I therefore suggest the following: https://github.com/jborg/attic/issues/217#issuecomment-100895815

**Comment by ThomasWaldmann** [comment]
@maltefiala you can also edit your ticket's/comment's text or even delete (your) comments.

for chatting, come to freenode IRC #borg-backup. :)
