### ISSUE TITLE
Borg, James Borg

### ISSUE THREAD

**Issue by aride** [borg-backup/borg-backup.github.io#2]
Hey, I have my doubts about this project's name. I think if a fork happens, it will be confusing (is Borg backup really J. Borg's backup software?). I think you probably came up with it as an homage to jborg, but he might take it as a jab (would you like someone to use your last name like that?). Of course I appreciate the humor in the name, but still...

**Comment by ThomasWaldmann** [comment]
His name is Jonas Borgström.

The Borg Collective is assimilating species and technologies that are useful and it strives for perfection, even for their backup solution.

:)
